import { reactive } from "vue";

const state = reactive({
  navItems: [
    {
      root: "/artisans",
      to: "/artisans",
      icon: "eva-globe-outline",
    },
    {
      root: "/light",
      to: "/light",
      icon: "eva-bulb",
    },
    {
      root: "/profile",
      to: "/profile",
      icon: "eva-square",
    },
  ],
  usePageTransition: false,
  theme: "dim-background", // Default theme
  textColor: "green", // Default text color
  textColorOptions: {
    "bright-background": ["black", "green"],
    "dim-background": ["black", "green"],
    "dark-background": ["white", "violet", "green"],
  },
  locations: [
    {
      id: 1,
      name: "Mombasa",
      constituencies: [
        "Changamwe",
        "Kisauni",
        "Likoni",
        "Jomvu",
        "Nyali",
        "Mvita",
      ],
    },
    {
      id: 30,
      name: "Baringo",
      constituencies: [
        "Baringo Central",
        "Baringo North",
        "Mogotio",
        "Tiaty",
        "Eldama Ravine",
        "Baringo South",
      ],
    },
    {
      id: 36,
      name: "Bomet",
      constituencies: [
        "Bomet East",
        "Bomet Central",
        "Chepalungu",
        "Sotik",
        "Konoin",
      ],
    },

    {
      id: 39,
      name: "Bungoma",
      constituencies: [
        "Bumula",
        "Kabuchai",
        "Kanduyi",
        "Kimilili",
        "Mt. Elgon",
        "Sirisia",
        "Tongaren",
        "Webuye East",
        "Webuye West",
      ],
    },
    {
      id: 40,
      name: "Busia",
      constituencies: [
        "Budalang'i",
        "Butula",
        "Funyula",
        "Matayos",
        "Nambale",
        "Teso North",
        "Teso South",
      ],
    },
    {
      id: 28,
      name: "Elgeyo-Marakwet",
      constituencies: [
        "Keiyo North",
        "Keiyo South",
        "Marakwet East",
        "Marakwet West",
      ],
    },
    {
      id: 14,
      name: "Embu",
      constituencies: ["Manyatta", "Mbeere North", "Mbeere South", "Runyenjes"],
    },
    {
      id: 7,
      name: "Garissa",
      constituencies: [
        "Balambala",
        "Dadaab",
        "Fafi",
        "Garissa Township",
        "Ijara",
        "Lagdera",
      ],
    },
    {
      id: 43,
      name: "Homa Bay",
      constituencies: [
        "Homa Bay Town",
        "Kabondo Kasipul",
        "Karachuonyo",
        "Kasipul",
        "Ndhiwa",
        "Rangwe",
        "Suba North",
        "Suba South",
      ],
    },
    {
      id: 11,
      name: "Isiolo",
      constituencies: ["Isiolo North", "Isiolo South"],
    },
    {
      id: 34,
      name: "Kajiado",
      constituencies: [
        "Kajiado Central",
        "Kajiado East",
        "Kajiado North",
        "Kajiado South",
        "Kajiado West",
      ],
    },
    {
      id: 37,
      name: "Kakamega",
      constituencies: [
        "Butere",
        "Ikolomani",
        "Khwisero",
        "Lugari",
        "Lurambi",
        "Malava",
        "Matungu",
        "Mumias East",
        "Mumias West",
        "Navakholo",
        "Shinyalu",
      ],
    },
    {
      id: 35,
      name: "Kericho",
      constituencies: [
        "Ainamoi",
        "Belgut",
        "Bureti",
        "Kipkelion East",
        "Kipkelion West",
        "Sigowet-Soin",
      ],
    },
    {
      id: 22,
      name: "Kiambu",
      constituencies: [
        "Gatundu North",
        "Gatundu South",
        "Githunguri",
        "Juja",
        "Kabete",
        "Kiambaa",
        "Kiambu",
        "Kikuyu",
        "Limuru",
        "Lari",
        "Ruiru",
        "Thika Town",
      ],
    },
    {
      id: 3,
      name: "Kilifi",
      constituencies: [
        "Ganze",
        "Kaloleni",
        "Kilifi North",
        "Kilifi South",
        "Magarini",
        "Malindi",
        "Rabai",
      ],
    },
    {
      id: 20,
      name: "Kirinyaga",
      constituencies: ["Gichugu", "Kirinyaga Central", "Mwea", "Ndia"],
    },
    {
      id: 45,
      name: "Kisii",
      constituencies: [
        "Bobasi",
        "Bomachoge Borabu",
        "Bomachoge Chache",
        "Bonchari",
        "Kitutu Chache North",
        "Kitutu Chache South",
        "Nyaribari Chache",
        "Nyaribari Masaba",
        "South Mugirango",
      ],
    },
    {
      id: 42,
      name: "Kisumu",
      constituencies: [
        "Kisumu East",
        "Kisumu West",
        "Kisumu Central",
        "Nyakach",
        "Nyando",
        "Seme",
      ],
    },
    {
      id: 15,
      name: "Kitui",
      constituencies: [
        "Kitui Central",
        "Kitui East",
        "Kitui Rural",
        "Kitui South",
        "Kitui West",
        "Mwingi Central",
        "Mwingi North",
        "Mwingi West",
      ],
    },
    {
      id: 2,
      name: "Kwale",
      constituencies: ["Kinango", "Lungalunga", "Matuga", "Msambweni"],
    },
    {
      id: 31,
      name: "Laikipia",
      constituencies: ["Laikipia East", "Laikipia North", "Laikipia West"],
    },
    {
      id: 5,
      name: "Lamu",
      constituencies: ["Lamu East", "Lamu West"],
    },
    {
      id: 16,
      name: "Machakos",
      constituencies: [
        "Kangundo",
        "Kathiani",
        "Machakos Town",
        "Masinga",
        "Matungulu",
        "Mavoko",
        "Mwala",
        "Yatta",
      ],
    },
    {
      id: 17,
      name: "Makueni",
      constituencies: [
        "Emali/Mulala",
        "Kaiti",
        "Kibwezi East",
        "Kibwezi West",
        "Kilome",
        "Makueni",
        "Mbooni",
      ],
    },
    {
      id: 9,
      name: "Mandera",
      constituencies: [
        "Banissa",
        "Lafey",
        "Mandera East",
        "Mandera North",
        "Mandera South",
        "Mandera West",
      ],
    },
    {
      id: 12,
      name: "Meru",
      constituencies: [
        "Buuri",
        "Central Imenti",
        "Igembe Central",
        "Igembe North",
        "Igembe South",
        "North Imenti",
        "South Imenti",
        "Tigania East",
        "Tigania West",
      ],
    },
    {
      id: 44,
      name: "Migori",
      constituencies: [
        "Awendo",
        "Kuria East",
        "Kuria West",
        "Nyatike",
        "Rongo",
        "Suna East",
        "Suna West",
        "Uriri",
      ],
    },
    {
      id: 10,
      name: "Marsabit",
      constituencies: ["Laisamis", "Moyale", "North Horr", "Saku"],
    },
    {
      id: 21,
      name: "Murang'a",
      constituencies: [
        "Gatanga",
        "Kandara",
        "Kangema",
        "Kiharu",
        "Kigumo",
        "Maragua",
        "Mathioya",
      ],
    },
    {
      id: 47,
      name: "Nairobi",
      constituencies: [
        "Dagoretti North",
        "Dagoretti South",
        "Embakasi Central",
        "Embakasi East",
        "Embakasi North",
        "Embakasi South",
        "Embakasi West",
        "Kamukunji",
        "Kasarani",
        "Kibra",
        "Lang'ata",
        "Makadara",
        "Mathare",
        "Roysambu",
        "Ruaraka",
        "Starehe",
        "Westlands",
      ],
    },
    {
      id: 32,
      name: "Nakuru",
      constituencies: [
        "Bahati",
        "Gilgil",
        "Kuresoi North",
        "Kuresoi South",
        "Molo",
        "Naivasha",
        "Nakuru Town East",
        "Nakuru Town West",
        "Njoro",
        "Rongai",
        "Subukia",
      ],
    },
    {
      id: 29,
      name: "Nandi",
      constituencies: [
        "Aldai",
        "Chesumei",
        "Emgwen",
        "Mosop",
        "Nandi Hills",
        "Tindiret",
      ],
    },
    {
      id: 33,
      name: "Narok",
      constituencies: [
        "Emurua Dikirr",
        "Kilgoris",
        "Narok East",
        "Narok North",
        "Narok South",
        "Narok West",
      ],
    },
    {
      id: 46,
      name: "Nyamira",
      constituencies: [
        "Borabu",
        "Manga",
        "Masaba North",
        "Nyamira North",
        "West Mugirango",
      ],
    },
    {
      id: 18,
      name: "Nyandarua",
      constituencies: [
        "Kinangop",
        "Kipipiri",
        "Ol Kalou",
        "Ol Jorok",
        "Ndaragua",
      ],
    },
    {
      id: 19,
      name: "Nyeri",
      constituencies: ["Tetu", "Othaya", "Kieni", "Mathira", "Nyeri Town"],
    },
    {
      id: 41,
      name: "Siaya",
      constituencies: [
        "Ugenya",
        "Ugunja",
        "Alego Usonga",
        "Gem",
        "Bondo",
        "Rarieda",
      ],
    },

    {
      id: 38,
      name: "Vihiga",
      constituencies: ["Vihiga", "Sabatia", "Hamisi", "Luanda", "Emuhaya"],
    },
    {
      id: 27,
      name: "Uasin Gishu",
      constituencies: [
        "Soy",
        "Turbo",
        "Moiben",
        "Ainabkoi",
        "Kapseret",
        "Kesses",
      ],
    },
    {
      id: 26,
      name: "Trans Nzoia",
      constituencies: [
        "Kwanza",
        "Endebess",
        "Saboti",
        "Kiminini",
        "Cherangany",
      ],
    },
    {
      id: 25,
      name: "Samburu",
      constituencies: ["Samburu West", "Samburu East", "Samburu North"],
    },
    {
      id: 24,
      name: "West Pokot",
      constituencies: ["Kapenguria", "Sigor", "Kacheliba", "Pokot South"],
    },
    {
      id: 23,
      name: "Turkana",
      constituencies: [
        "Turkana West",
        "Turkana North",
        "Turkana Central",
        "Turkana East",
        "Turkana South",
        "Loima",
      ],
    },
    {
      id: 13,
      name: "Tharaka-Nithi",
      constituencies: ["Maara", "Tharaka", "Chuka"],
    },
    {
      id: 8,
      name: "Wajir",
      constituencies: [
        "Wajir West",
        "Wajir North",
        "Tarbaj",
        "Wajir East",
        "Wajir South",
        "Eldas",
      ],
    },

    {
      id: 4,
      name: "Tana River",
      constituencies: ["Garson", "Kalole", "Bura"],
    },
    {
      id: 6,
      name: "Taita-Taveta",
      constituencies: [
        "Taveta",
        "Voi",
        "Wundanyi",
        "Mwatate",
        "Turkana South",
        "Loima",
      ],
    },
  ],
  artisans: [
    {
      id: 3,
      name: "Elijah Wangari",
      craft: "Electrician",
      location: "Ruiru",
      county: "Kiambu",
      email: "",
      phone: "0791777978",
      showContact: false,
    },
    {
      id: 4,
      name: "Joachim Kibathi",
      craft: "Plumber",
      location: "Juja",
      county: "Kiambu",
      email: "",
      phone: "0724356177",
      showContact: false,
    },
    {
      id: 5,
      name: "Justus Kariuki",
      craft: "Plumber",
      location: "Nyeri Town",
      county: "Nyeri",
      email: "",
      phone: "0757460774",
      showContact: false,
    },
    {
      id: 6,
      name: "David Mbugua",
      craft: "Chef",
      location: "Ruiru",
      county: "Kiambu",
      email: "",
      phone: "0703148750",
      showContact: false,
    },
    {
      id: 7,
      name: "Samwel Thuo",
      craft: "Plumber",
      location: "Ruiru",
      county: "Kiambu",
      email: "",
      phone: "0707080474",
      showContact: false,
    },
    {
      id: 8,
      name: "Denis Mbugua",
      craft: "Helper",
      location: "Machakos Town",
      county: "Machakos",
      email: "",
      phone: "0718214511",
      showContact: false,
    },
    {
      id: 9,
      name: "Ephraim Bosire",
      craft: "Helper",
      location: "Juja",
      county: "Kiambu",
      email: "",
      phone: "0791325823",
      showContact: false,
    },
    {
      id: 10,
      name: "Kim",
      craft: "Plumber",
      location: "Juja",
      county: "Kiambu",
      email: "",
      phone: "0794341720",
      showContact: false,
    },
  ],
});

const store = {
  state,
};

export default store;
